AMQP_URI: 'amqp://guest:guest@croquemort-rabbitmq'
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
rpc_exchange: 'nameko-rpc'
max_workers: 10
parent_calls_tracked: 10
REDIS_URI: 'redis://croquemort-redis:6379/5'
CRAWLER_GET_TIMEOUT: 180
CRAWLER_HEAD_TIMEOUT: 10
HEAD_DOMAINS_BLACKLIST: []
LOGGING:
    version: 1
    formatters:
      timestamped:
        format: '[%(asctime)s] %(levelname)-8s %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: timestamped
    root:
        level: INFO
        handlers: [console]
