croquemort-redis:
    image: redis
croquemort-rabbitmq:
    image: rabbitmq:3.5-management
    environment:
      RABBITMQ_NODENAME: croquemort
croquemort:
  build: .
  links:
    - croquemort-redis
    - croquemort-rabbitmq
  ports:
    - "8000:8000"
  environment:
    - http_proxy
    - https_proxy
  entrypoint: ./wait-for-it.sh -t 15 croquemort-rabbitmq:5672 -- honcho start
